services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: screenshots
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        environment:
            - REDIS_HOST=127.0.0.1
            - REDIS_PASSWORD=null
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: php/Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: laravel_app
        volumes:
            - ./laravel:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
        ports:
            - "8080:8080" #reverb port
            - "5173:5173"
        networks:
            - laravel
        depends_on:
          mariadb:
            condition: service_healthy
          redis:
            condition: service_started

    web:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "4242:80"
        volumes:
            - ./laravel:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8888:80"
        depends_on:
            - mariadb
        networks:
            - laravel

    minio:
        image: minio/minio:latest
        container_name: minio
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "8900:8900"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        volumes:
            - minio:/data/minio
        command: 'minio server /data/minio --console-address ":8900"'
        networks:
            - laravel

volumes:
    minio:
    dbdata:

networks:
    laravel:
        driver: bridge
